INSERT INTO ARTICLE(ARTICLEID, EMAIL, CONTENT, TITLE, CreationTime)
VALUES (ARTICLE_SQL.NEXTVAL, 'LOVE@NAVER.COM', '내용입니다.', '제목입니다.', '2023-02-12');

INSERT INTO ARTICLE(ARTICLEID, EMAIL, CONTENT, TITLE, CreationTime)
VALUES (ARTICLE_SQL.NEXTVAL, 'TITLE@NAVER.COM', '내용입니다.', '제목입니다.', '2023-02-13');

INSERT INTO ARTICLE(ARTICLEID, EMAIL, CONTENT, TITLE, CreationTime)
VALUES (ARTICLE_SQL.NEXTVAL, 'CONTENT@NAVER.COM', '내용입니다.', '제목입니다.', '2023-02-14');

INSERT INTO ARTICLE(ARTICLEID, EMAIL, CONTENT, TITLE, CreationTime)
VALUES (ARTICLE_SQL.NEXTVAL, 'PO@NAVER.COM', '내용입니다.', '제목입니다.', '2023-02-15');