INSERT INTO CUSTOMER(ID, USERNAME, PASSWORD, EMAIL, PHONE, AUTH)
VALUES(CUSTOMER_SQL.NEXTVAL, '홍길동', '1234', 'LOVE@NAVER.COM', '010-0000-0000', 'USER');

INSERT INTO CUSTOMER(ID, USERNAME, PASSWORD, EMAIL, PHONE, AUTH)
VALUES(CUSTOMER_SQL.NEXTVAL, '일길동', '1234', 'TITLE@NAVER.COM', '010-1111-1111', 'USER');

INSERT INTO CUSTOMER(ID, USERNAME, PASSWORD, EMAIL, PHONE, AUTH)
VALUES(CUSTOMER_SQL.NEXTVAL, '이길동', '1234', 'CONTENT@NAVER.COM', '010-2222-2222', 'USER');

INSERT INTO CUSTOMER(ID, USERNAME, PASSWORD, EMAIL, PHONE, AUTH)
VALUES(CUSTOMER_SQL.NEXTVAL, '삼길동', '1234', 'PO@NAVER.COM', '010-3333-3333', 'USER');